"""
Fetch Google Scholar stats and update README.md with live data.
Uses the scholarly library with fallback to direct HTML scraping.
Designed to run in GitHub Actions on a weekly schedule.
"""

import re
import json
import os
import sys
import time
from pathlib import Path
from datetime import datetime, timezone


def fetch_with_scholarly(scholar_id: str) -> dict | None:
    """Fetch author stats using the scholarly library."""
    try:
        from scholarly import scholarly

        search = scholarly.search_author_id(scholar_id)
        author = scholarly.fill(search, sections=["basics", "indices", "publications"])

        publications = author.get("publications", [])
        pub_count = len(publications)
        citations = author.get("citedby", 0)
        h_index = author.get("hindex", 0)
        i10_index = author.get("i10index", 0)

        # Get top 5 cited papers
        top_papers = []
        for pub in sorted(publications, key=lambda p: p.get("num_citations", 0), reverse=True)[:5]:
            bib = pub.get("bib", {})
            top_papers.append({
                "title": bib.get("title", "Unknown"),
                "citations": pub.get("num_citations", 0),
                "year": bib.get("pub_year", "N/A"),
            })

        return {
            "citations": citations,
            "h_index": h_index,
            "i10_index": i10_index,
            "pub_count": pub_count,
            "top_papers": top_papers,
        }
    except Exception as e:
        print(f"[scholarly] Failed: {e}")
        return None


def fetch_with_requests(scholar_id: str) -> dict | None:
    """Fallback: scrape Google Scholar profile page directly."""
    try:
        import requests
        from bs4 import BeautifulSoup

        url = f"https://scholar.google.com/citations?user={scholar_id}&hl=en"
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            )
        }

        resp = requests.get(url, headers=headers, timeout=30)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")

        # Extract citation indices table
        index_cells = soup.select("#gsc_rsb_st td.gsc_rsb_std")
        if len(index_cells) >= 2:
            citations = int(index_cells[0].text.strip())
            h_index = int(index_cells[2].text.strip())
            i10_index = int(index_cells[4].text.strip()) if len(index_cells) > 4 else 0
        else:
            return None

        # Count publications
        pub_rows = soup.select("#gsc_a_b .gsc_a_tr")
        pub_count = len(pub_rows)

        # Get top papers from the visible table
        top_papers = []
        for row in pub_rows[:5]:
            title_el = row.select_one(".gsc_a_at")
            cite_el = row.select_one(".gsc_a_c a")
            year_el = row.select_one(".gsc_a_y span")
            if title_el:
                top_papers.append({
                    "title": title_el.text.strip(),
                    "citations": int(cite_el.text.strip()) if cite_el and cite_el.text.strip() else 0,
                    "year": year_el.text.strip() if year_el else "N/A",
                })

        return {
            "citations": citations,
            "h_index": h_index,
            "i10_index": i10_index,
            "pub_count": pub_count,
            "top_papers": top_papers,
        }
    except Exception as e:
        print(f"[requests] Failed: {e}")
        return None


def update_readme(stats: dict, readme_path: str = "README.md") -> bool:
    """Replace content between marker comments in README.md."""
    path = Path(readme_path)
    content = path.read_text(encoding="utf-8")

    now = datetime.now(timezone.utc).strftime("%B %d, %Y")

    # Build the stats block
    top_papers_rows = ""
    for p in stats.get("top_papers", [])[:5]:
        title = p["title"]
        if len(title) > 70:
            title = title[:67] + "..."
        top_papers_rows += f"| {title} | {p['citations']:,} | {p['year']} |\n"

    stats_block = f"""<!-- SCHOLAR_STATS:START - Auto-generated by GitHub Action, do not edit -->
<table>
  <tr>
    <td align="center"><strong>{stats['citations']:,}</strong><br/>Citations</td>
    <td align="center"><strong>{stats['h_index']}</strong><br/>h-index</td>
    <td align="center"><strong>{stats['i10_index']}</strong><br/>i10-index</td>
    <td align="center"><strong>{stats['pub_count']}+</strong><br/>Publications</td>
  </tr>
</table>

<sub>Last updated: {now} | Source: <a href="https://scholar.google.com/citations?user={os.environ.get('SCHOLAR_ID', 'OaFJvaIAAAAJ')}&hl=en">Google Scholar</a></sub>
<!-- SCHOLAR_STATS:END -->"""

    # Replace between markers
    pattern = r"<!-- SCHOLAR_STATS:START.*?-->.*?<!-- SCHOLAR_STATS:END -->"
    new_content, count = re.subn(pattern, stats_block, content, flags=re.DOTALL)

    if count == 0:
        print("[ERROR] Could not find SCHOLAR_STATS markers in README.md")
        return False

    path.write_text(new_content, encoding="utf-8")
    print(f"[OK] README updated: {stats['citations']:,} citations, h-index {stats['h_index']}, {stats['pub_count']}+ publications")
    return True


def main():
    scholar_id = os.environ.get("SCHOLAR_ID", "OaFJvaIAAAAJ")
    readme_path = os.environ.get("README_PATH", "README.md")

    print(f"Fetching stats for Scholar ID: {scholar_id}")

    # Try scholarly first, fall back to direct scraping
    stats = fetch_with_scholarly(scholar_id)
    if stats is None:
        print("Trying fallback method...")
        time.sleep(2)
        stats = fetch_with_requests(scholar_id)

    if stats is None:
        print("[ERROR] Could not fetch scholar stats with any method.")
        # Save last known stats if available
        cache_path = Path("scholar_cache.json")
        if cache_path.exists():
            print("[INFO] Using cached stats from previous run.")
            stats = json.loads(cache_path.read_text())
        else:
            sys.exit(1)

    # Cache the stats for future fallback
    Path("scholar_cache.json").write_text(json.dumps(stats, indent=2))

    if not update_readme(stats, readme_path):
        sys.exit(1)


if __name__ == "__main__":
    main()
