"""
Fetch Google Scholar stats via SerpAPI and update README.md.
SerpAPI free tier: 100 searches/month (we use ~4/month).
Sign up at https://serpapi.com to get your API key.
"""

import re
import json
import os
import sys
import time
from pathlib import Path
from datetime import datetime, timezone
import requests


SCHOLAR_ID = os.environ.get("SCHOLAR_ID", "OaFJvaIAAAAJ")
SERPAPI_KEY = os.environ.get("SERPAPI_KEY", "")
README_PATH = os.environ.get("README_PATH", "README.md")


def fetch_google_scholar(scholar_id: str, api_key: str) -> dict | None:
    """Fetch author stats from Google Scholar via SerpAPI."""
    try:
        # Get author profile with citation stats
        url = "https://serpapi.com/search.json"
        params = {
            "engine": "google_scholar_author",
            "author_id": scholar_id,
            "api_key": api_key,
        }

        print(f"[GS] Fetching profile for author ID: {scholar_id}")
        resp = requests.get(url, params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()

        # Extract citation stats
        cited_by = data.get("cited_by", {})
        table = cited_by.get("table", [])

        citations_all = 0
        h_index = 0
        i10_index = 0

        for row in table:
            if "citations" in row:
                citations_all = row["citations"].get("all", 0)
            elif "h_index" in row:
                h_index = row["h_index"].get("all", 0)
            elif "i10_index" in row:
                i10_index = row["i10_index"].get("all", 0)

        # Extract top articles (sorted by citations by default)
        articles = data.get("articles", [])
        top_papers = []
        for article in articles[:5]:
            top_papers.append({
                "title": article.get("title", "Unknown"),
                "citations": article.get("cited_by", {}).get("value", 0),
                "year": article.get("year", "N/A") or "N/A",
            })

        # Count total publications from the first page
        pub_count = len(articles)

        # Paginate to count all publications (uses 1 API call per page)
        next_link = data.get("serpapi_pagination", {}).get("next")
        while next_link and pub_count < 500:
            time.sleep(1)
            resp2 = requests.get(next_link + f"&api_key={api_key}", timeout=30)
            if resp2.ok:
                page_data = resp2.json()
                page_articles = page_data.get("articles", [])
                if not page_articles:
                    break
                pub_count += len(page_articles)
                next_link = page_data.get("serpapi_pagination", {}).get("next")
            else:
                break

        author_name = data.get("author", {}).get("name", "Unknown")
        stats = {
            "citations": citations_all,
            "h_index": h_index,
            "i10_index": i10_index,
            "pub_count": pub_count,
            "top_papers": top_papers,
            "source": "Google Scholar",
        }
        print(f"[GS] Success for {author_name}: {stats['citations']:,} citations, "
              f"h-index {stats['h_index']}, i10-index {stats['i10_index']}, "
              f"{stats['pub_count']} publications")
        return stats

    except requests.exceptions.HTTPError as e:
        if e.response is not None and e.response.status_code == 401:
            print("[GS] ERROR: Invalid SerpAPI key. Check your SERPAPI_KEY secret.")
        else:
            print(f"[GS] HTTP error: {e}")
        return None
    except Exception as e:
        print(f"[GS] Failed: {e}")
        return None


def update_readme(stats: dict, readme_path: str = "README.md") -> bool:
    """Replace content between marker comments in README.md."""
    path = Path(readme_path)
    content = path.read_text(encoding="utf-8")

    now = datetime.now(timezone.utc).strftime("%B %d, %Y")
    scholar_link = f"https://scholar.google.com/citations?user={SCHOLAR_ID}&hl=en"

    stats_block = f"""<!-- SCHOLAR_STATS:START - Auto-generated by GitHub Action, do not edit -->
<table>
  <tr>
    <td align="center"><strong>{stats['citations']:,}</strong><br/>Citations</td>
    <td align="center"><strong>{stats['h_index']}</strong><br/>h-index</td>
    <td align="center"><strong>{stats['i10_index']}</strong><br/>i10-index</td>
    <td align="center"><strong>{stats['pub_count']}</strong><br/>Publications</td>
  </tr>
</table>

<sub>Last updated: {now} via {stats.get('source', 'Google Scholar')} | <a href="{scholar_link}">View full profile</a></sub>
<!-- SCHOLAR_STATS:END -->"""

    pattern = r"<!-- SCHOLAR_STATS:START.*?-->.*?<!-- SCHOLAR_STATS:END -->"
    new_content, count = re.subn(pattern, stats_block, content, flags=re.DOTALL)

    if count == 0:
        print("[ERROR] Could not find SCHOLAR_STATS markers in README.md")
        return False

    path.write_text(new_content, encoding="utf-8")
    print(f"[OK] README updated with Google Scholar data")
    return True


def main():
    if not SERPAPI_KEY:
        print("[ERROR] SERPAPI_KEY not set. Add it as a repository secret.")
        print("  1. Go to https://serpapi.com and sign up (free)")
        print("  2. Copy your API key")
        print("  3. In your repo: Settings > Secrets > Actions > New secret")
        print("     Name: SERPAPI_KEY")
        print("     Value: your-api-key")
        sys.exit(1)

    print(f"Fetching Google Scholar stats for ID: {SCHOLAR_ID}")
    stats = fetch_google_scholar(SCHOLAR_ID, SERPAPI_KEY)

    if stats is None:
        cache_path = Path("scholar_cache.json")
        if cache_path.exists():
            print("[INFO] Using cached stats from previous run.")
            stats = json.loads(cache_path.read_text())
        else:
            print("[ERROR] Could not fetch stats and no cache available.")
            sys.exit(1)

    # Cache for future fallback
    Path("scholar_cache.json").write_text(json.dumps(stats, indent=2))

    if not update_readme(stats, README_PATH):
        sys.exit(1)


if __name__ == "__main__":
    main()
